### ISSUE TITLE
Windows \r\n line separators not completely removed

### ISSUE THREAD

**Issue by ZabutonNage** [XploreX/node-file-dialog#2]
**What version of this package are you using?**
`1.0.3`

**What operating system, Node.js, and npm version?**
`Win10`, Node `15.14.0`, npm `7.7.6`

**What happened?**
Used the `open-files` config to open multiple files.
Returned array elements contained trailing `\r` characters:
```js
[ "file00\r", "file01\r", "file02"]
```

**What did you expect to happen?**
Windows' `\r\n` line separators should be completely removed.

**Are you willing to submit a pull request to fix this bug?**
Yes

Using `require("os").EOL` when splitting the output from `stdout` [here](https://github.com/manorit2001/node-file-dialog/blob/main/index.js#L33) fixed it for me.

**Comment by manorit2001** [comment]
Hi @ZabutonNage, can you please open a PR with the fix?
